task:
  name: Windows
  windows_container:
    dockerfile: ci/Dockerfile
  build_script:
      - dir /s /b "c:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC"
      - cd "c:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Auxiliary/Build"
      - vcvarsall x64
